In [2]:
# numpy 실습문제

# B15. 30부터 70까지 짝수로 이루어진 array를 만드시오 

import numpy as np

evenNum = np.arange(30,71,2)
evenNum

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [5]:
# B13. 10개의 zero, 10개의 one, 10개의 5로 만들어진 array를 각각 만드시오

import numpy as np

tenZero = np.zeros(10)
tenOne = np.ones(10)
tenFive = np.ones(10)*5

print(tenZero)
print(tenOne)
print(tenFive)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [6]:
# B19. 15부터 55까지 수로 구성된 array에서 첫 요소와 마지막 요소를 제외하고 모두 print하는 코드를 작성하시오

import numpy as np

myArray = np.arange(15,56)

for i in myArray:
    if i == 15 or i == 55:
        continue
    print(i)

# -1번째 (맨 마지막)은 포함되지 않음
print(myArray[1:-1])

16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [9]:
# B20. 10부터 21까지 정수로 구성되는  3x4 array를 만드시오.

import numpy as np

arr = np.arange(10,22).reshape(3,4)
print(arr)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [10]:
# B21. 5부터 50까지 10개의 요소를 등간격으로 구성하는 array를 만드시오 
# 등간격은 linspace

import numpy as np

# linspace는 마지막 숫자인 50이 포함된다!!!
myArr = np.linspace(5, 50, 10)
print(myArr)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [11]:
# B22. 0-20까지 값을 가지는 array에서 9부터 15까지의 요소를 음수로 바꾸시오 
# 주의!! 인덱스를 통해 접근하고, 값을 배열에 직접 넣기!

import numpy as np

myArray = np.arange(0,21)

for i in range(0,21):
    if 9 <= i and i <= 15:
        myArray[i] = -i
        
print(myArray)



x = np.arange(21)
x[(x >= 9) & (x <= 15)] *= -1
print(x)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [15]:
# B23. 임의의 수로 이루어진 3x4 array를 생성하시오 

import numpy as np

a = np.random.random([3,4])
print(a)

[[0.85504079 0.38078659 0.68602908 0.73131362]
 [0.21630817 0.02106764 0.5929057  0.72616284]
 [0.84310982 0.62180009 0.49477861 0.65317155]]


In [18]:
# B24.(random.randint()) 0~100 중 임의의 integer 12개로 이루어진 3x4 array를 생성하시오 

import numpy as np

b = np.random.randint(0,101,12).reshape(3,4)
print(b)

[[ 35   8  72  84]
 [ 92  29 100  82]
 [ 55  60   7  15]]


In [21]:
# B28. 10x10 array를 만들어 가운데는 zero 가장자리는 1로 채우시오

import numpy as np

c = np.zeros([10, 10])

for i in range(0, 10):
    for j in range(0, 10):
        if i == 0 or i == 9 or j == 0 or j == 9:
            c[i][j] = 1

print(c)

c = np.ones([10, 10])
print(c)
# -1은 포함이 안되므로, 이 앞인 -2까지 적용
c[1:-1, 1:-1] = 0
print(c)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [22]:
# A90. 주어진 array에서 음수를 zero로 바꾸시오

import numpy as np

x = np.array([-1, -4, 0, 2, 3, 4, 5, -6])

for i in range(len(x)):
    if x[i] < 0:
        x[i] = 0

print(x)




x[x < 0] = 0

print(x)

[0 0 0 2 3 4 5 0]
[0 0 0 2 3 4 5 0]


In [25]:
# A88. 6x6 random array를 만들어 .5보다 큰 요소는 값을 0.5로 바꾸시오.

import numpy as np

randArray = np.random.random([6,6])
for i in range(6):
    for j in range(6):
        if randArray[i][j] > 0.5:
            randArray[i][j] = 0.5

print(randArray)
            
    
    
randArray[randArray > .5] = .5
print(randArray)

[[0.5        0.5        0.33264781 0.5        0.00096707 0.5       ]
 [0.5        0.5        0.5        0.01939149 0.43900726 0.42846014]
 [0.21960772 0.27093064 0.02918032 0.5        0.3280272  0.5       ]
 [0.07748644 0.37862192 0.5        0.5        0.17946224 0.5       ]
 [0.5        0.3603441  0.5        0.27595612 0.5        0.21018376]
 [0.5        0.5        0.18763678 0.5        0.5        0.5       ]]
[[0.5        0.5        0.33264781 0.5        0.00096707 0.5       ]
 [0.5        0.5        0.5        0.01939149 0.43900726 0.42846014]
 [0.21960772 0.27093064 0.02918032 0.5        0.3280272  0.5       ]
 [0.07748644 0.37862192 0.5        0.5        0.17946224 0.5       ]
 [0.5        0.3603441  0.5        0.27595612 0.5        0.21018376]
 [0.5        0.5        0.18763678 0.5        0.5        0.5       ]]
