In [1]:
import numpy as np

# 인덱싱

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

# 튜플의 방식을 통해 인덱싱 진행
a[(0,0)]

1

In [40]:
# C언어처럼 배열 접근 가능
a[1][2]

7

In [39]:
# 튜플이 아니어도 인덱싱 가능
a[1,2]

7

In [38]:
# -를 통해 뒤에서부터 접근도 가능
a[-1][-1]

22

In [4]:
# 연산을 통해 값 바꾸기
a[-1, -1] += 10
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 22]]


In [5]:
# 슬라이싱

# 1행 전부 출력 -> 0부터 시작!!!

a[0,:]

array([1, 2, 3, 4])

In [7]:
# 모든 행과 1,2열 모두 출력 -> 0부터 시작!!!

a[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [8]:
## 열에 간격 주기
# 4열까지!!(3이므로), 2칸의 간격으로

a[:,:3:2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [9]:
# 뒤에서부터 거꾸로 열에 간격 주기
# -를 통해 간격 조정!!

a[:,-1:-4:-2]

array([[ 4,  2],
       [ 8,  6],
       [22, 10]])

In [10]:
## 열의 위치 내 맘대로 조정

a[:,[3,0,2,1]]

array([[ 4,  1,  3,  2],
       [ 8,  5,  7,  6],
       [22,  9, 11, 10]])

In [11]:
## 원하는 값 추출

# (0,0), (1,1), (2,2)에 해당하는 값을 array로 반환
a[[0,1,2],[0,1,2]]

array([ 1,  6, 11])

In [13]:
c = np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
# 11부터 16까지 수를 만들고, 2행 3열로 만든다.
d = np.arange(11,17).reshape(2,3)
d

array([[11, 12, 13],
       [14, 15, 16]])

In [16]:
# 행과 열이 같은 c와 d는 연산이 가능!
c + d

array([[12, 14, 16],
       [18, 20, 22]])

In [17]:
c - d

array([[-10, -10, -10],
       [-10, -10, -10]])

In [18]:
c * d

array([[11, 24, 39],
       [56, 75, 96]])

In [20]:
c / d

array([[0.09090909, 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     ]])

In [24]:
c**2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [23]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
np.sqrt(c)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [28]:
# 행렬의 곱연산, 곱연산을 위해 d를 transpose해준다.
np.dot(c, d.transpose())

array([[ 74,  92],
       [182, 227]])

In [31]:
# transpose() 는 T로 나타낼 수 있다.
np.dot(c.T, d)

array([[ 67,  72,  77],
       [ 92,  99, 106],
       [117, 126, 135]])

In [32]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 22]])

In [33]:
# a가 5보다 큰 값은 True, 아닌 값은 False로 나타낸다.

a > 5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [35]:
# a가 5보다 큰 값들을 array로 추출한다. 다만, 2차원이 아닌 1차원으로 쭉 나열된다.

a[a > 5]

array([ 6,  7,  8,  9, 10, 11, 22])

In [36]:
# a 전체를 copy

b = a[:]
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 22]])

In [37]:
# 짝수에 해당하는 값만 리턴

b[b%2==0]

array([ 2,  4,  6,  8, 10, 22])